name = "RetryManagers"
uuid = "7a8cfeaa-437c-4519-b75e-06295593f538"
authors = ["meggart <fabiangans@gmx.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
Distributed = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
